### ISSUE TITLE
BUG: Line height 2em breaking design

### ISSUE THREAD

**Issue by jimblue** [MaxArt2501/share-this#14] opened 2017-10-31 23:03 UTC
Hi @MaxArt2501 !

I have a new train coding chalenge for you haha.

There is a little gap in the bottom of each buttons. (easier to see on hover)

The problem come from the line-height property set to 2em on `.share-this-popover>ul>li`.
It should be reset to 1 without unit.

That's it 😄

**Comment by jimblue** [comment] 2017-10-31 23:05
![line-height-0](https://user-images.githubusercontent.com/10623367/32252932-6dae3e4c-be98-11e7-812d-3bb9b64ff648.jpg)
![line-height-2](https://user-images.githubusercontent.com/10623367/32252933-6dca87dc-be98-11e7-8b75-8996a1df3ebe.jpg)

**Comment by MaxArt2501** [comment] 2017-11-20 22:56
I'm not able to reproduce the issue. In the [example page](https://maxart2501.github.io/share-this/) it works as intended.

Can you provide a minmal example?

**Comment by MaxArt2501** [comment] 2017-12-30 17:42
Closing as unable to reproduce the case.

**Closed by MaxArt2501** 2017-12-30 17:42 UTC

**Comment by jimblue** [comment] 2017-12-30 23:55
I've try to understand it but I didn't... I'll come back with more information asap.

Thanks
